# Generated by Django 3.1.3 on 2020-11-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201121_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, 'pending'), (1, 'complete')], default='pending', max_length=10),
        ),
    ]
